name: Run PowerShell Script and Upload File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # This runs the job every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: |
        .\RevitBuildChecker\generate_JSON.ps1
      working-directory: ${{ github.workspace }}
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add RevitBuildChecker\dist\RevitVersionsInfo.json
        git commit -m 'Update RevitVersionsInfo.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
